services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test:
        - CMD-SHELL
        - >
          sh -c "pg_isready -d '
            sslmode=verify-full
            sslrootcert=/var/lib/postgresql/ca.crt
            sslcert=/var/lib/postgresql/server.crt
            sslkey=/var/lib/postgresql/server.key
            user=$${POSTGRES_USER}
            password=$${POSTGRES_PASSWORD}
            dbname=$${POSTGRES_DB}
          '"
#      test: ["CMD-SHELL", "nc -z localhost 5432"]
      interval: 1s
      timeout: 5s
      retries: 10

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      ROOT_CERT_PATH: ca.pem
    command: ["--hostname", "0.0.0.0", "--port", "8080"]

volumes:
    postgres:
