services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: your_amazon_rds_database_endpoint
      DATABASE_PORT: 5432
      DATABASE_USER: your_amazon_rds_user_name
      DATABASE_PASSWORD: your_amazon_rds_password
      DATABASE_NAME: your_amazon_rds_database_name
      ROOT_CERT_PATH: eu-central-1-bundle.pem
    command: ["--hostname", "0.0.0.0", "--port", "8080"]
